// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSJy74tmbJmeXPyWv9QkIQ45UIBWkLZqM',
    appId: '1:642968386376:android:b0941bff15d0e9bc4bd17d',
    messagingSenderId: '642968386376',
    projectId: 'app-unialfa-50f41',
    storageBucket: 'app-unialfa-50f41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADzuw-7d3g0kotus8xL0X4cO3bkQcAynk',
    appId: '1:642968386376:ios:13a7b3c0dedf6cbd4bd17d',
    messagingSenderId: '642968386376',
    projectId: 'app-unialfa-50f41',
    storageBucket: 'app-unialfa-50f41.appspot.com',
    androidClientId: '642968386376-e04dfe0mepbt4c79vs44bo0323cmkbu1.apps.googleusercontent.com',
    iosClientId: '642968386376-7uujo89rfnovlpr28n6tjhurh7oi9dp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.appUnialfa',
  );
}
